[phases.setup]
nixPkgs = ["nodejs_22", "bun"]
aptPkgs = ["python3"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build --filter=web"]

[start]
cmd = "cd apps/web && bun start"

[variables]
NODE_ENV = "production"
PORT = "3001"