[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx turbo run build --filter=web"]

[start]
cmd = "cd apps/web && npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"